const std = @import("std");

pub const TokenType = enum {
    keyword,
    builtin,
    string,
    comment,
    number,
    operator,
    punctuation,
    type_name,
    function_name,
    default,
};

pub const zig_keywords = std.StaticStringMap(void).initComptime(.{
    .{ "const", {} },
    .{ "var", {} },
    .{ "fn", {} },
    .{ "pub", {} },
    .{ "return", {} },
    .{ "if", {} },
    .{ "else", {} },
    .{ "for", {} },
    .{ "while", {} },
    .{ "switch", {} },
    .{ "break", {} },
    .{ "continue", {} },
    .{ "defer", {} },
    .{ "errdefer", {} },
    .{ "try", {} },
    .{ "catch", {} },
    .{ "orelse", {} },
    .{ "and", {} },
    .{ "or", {} },
    .{ "error", {} },
    .{ "unreachable", {} },
    .{ "undefined", {} },
    .{ "null", {} },
    .{ "true", {} },
    .{ "false", {} },
    .{ "struct", {} },
    .{ "enum", {} },
    .{ "union", {} },
    .{ "packed", {} },
    .{ "extern", {} },
    .{ "export", {} },
    .{ "inline", {} },
    .{ "comptime", {} },
    .{ "test", {} },
    .{ "async", {} },
    .{ "await", {} },
    .{ "suspend", {} },
    .{ "resume", {} },
    .{ "anytype", {} },
    .{ "noreturn", {} },
    .{ "anyerror", {} },
    .{ "threadlocal", {} },
    .{ "linksection", {} },
    .{ "callconv", {} },
    .{ "noinline", {} },
    .{ "usingnamespace", {} },
    .{ "asm", {} },
    .{ "volatile", {} },
    .{ "allowzero", {} },
    .{ "align", {} },
});

pub const zig_builtins = std.StaticStringMap(void).initComptime(.{
    .{ "@import", {} },
    .{ "@as", {} },
    .{ "@intCast", {} },
    .{ "@floatCast", {} },
    .{ "@ptrCast", {} },
    .{ "@alignCast", {} },
    .{ "@enumFromInt", {} },
    .{ "@intFromEnum", {} },
    .{ "@intFromPtr", {} },
    .{ "@ptrFromInt", {} },
    .{ "@sizeOf", {} },
    .{ "@alignOf", {} },
    .{ "@typeInfo", {} },
    .{ "@TypeOf", {} },
    .{ "@This", {} },
    .{ "@tagName", {} },
    .{ "@errorName", {} },
    .{ "@fieldParentPtr", {} },
    .{ "@field", {} },
    .{ "@call", {} },
    .{ "@compileError", {} },
    .{ "@compileLog", {} },
    .{ "@panic", {} },
    .{ "@memcpy", {} },
    .{ "@memset", {} },
    .{ "@min", {} },
    .{ "@max", {} },
    .{ "@abs", {} },
    .{ "@mod", {} },
    .{ "@rem", {} },
    .{ "@sqrt", {} },
    .{ "@log", {} },
    .{ "@exp", {} },
    .{ "@sin", {} },
    .{ "@cos", {} },
    .{ "@tan", {} },
    .{ "@bitCast", {} },
    .{ "@truncate", {} },
    .{ "@ctz", {} },
    .{ "@clz", {} },
    .{ "@popCount", {} },
    .{ "@byteSwap", {} },
    .{ "@bitReverse", {} },
    .{ "@addWithOverflow", {} },
    .{ "@subWithOverflow", {} },
    .{ "@mulWithOverflow", {} },
    .{ "@shlWithOverflow", {} },
    .{ "@shlExact", {} },
    .{ "@shrExact", {} },
    .{ "@constCast", {} },
    .{ "@volatileCast", {} },
    .{ "@embedFile", {} },
    .{ "@cImport", {} },
    .{ "@cInclude", {} },
    .{ "@cDefine", {} },
    .{ "@cUndef", {} },
    .{ "@hasField", {} },
    .{ "@hasDecl", {} },
    .{ "@setRuntimeSafety", {} },
    .{ "@setFloatMode", {} },
    .{ "@setEvalBranchQuota", {} },
});

pub const zig_types = std.StaticStringMap(void).initComptime(.{
    .{ "void", {} },
    .{ "bool", {} },
    .{ "u8", {} },
    .{ "u16", {} },
    .{ "u32", {} },
    .{ "u64", {} },
    .{ "u128", {} },
    .{ "usize", {} },
    .{ "i8", {} },
    .{ "i16", {} },
    .{ "i32", {} },
    .{ "i64", {} },
    .{ "i128", {} },
    .{ "isize", {} },
    .{ "f16", {} },
    .{ "f32", {} },
    .{ "f64", {} },
    .{ "f128", {} },
    .{ "type", {} },
    .{ "comptime_int", {} },
    .{ "comptime_float", {} },
    .{ "anyframe", {} },
});
